### ISSUE TITLE
conda initialize

### ISSUE THREAD

**Issue by Dokmen** [TRUBA-HPC/Belgeler#8]
**Merhaba,

Python uygulaması için ben sizin ve wiki sayfasındaki adımları takip ederek hem anacondayı hem de jupyteri kurdum ancak interactive Rstrudio ortamı açtığımda R paketlerim artık çalışmıyor. Conda init çalıştırıp çalıştırmadığımı hatırlamıyorum ancak .bash_profile içinde aşağıdaki satırlar mevcut.** 

` # !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/truba/home/user/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
    #eval "$__conda_setup"
#else
    if [ -f "/truba/home/user/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/truba/home/user/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/truba/home/user/anaconda3/bin:$PATH"
    fi
#fi
#unset __conda_setup
` 

### **kurulumdan önceki durumu not almamışım. Session id'yi takip edip log dosyasına baktığımda ise aşağıdaki hatalar mevcut.**

` Show Dotfiles Show Owner/Mode
/truba/home/user/ondemand/data/sys/dashboard/batch_connect/sys/bc_rstudio/output/a5aa6950-1ffd-4dfa-9cf1-7378226c7b92/
Setting VNC password...
Starting VNC server...

Desktop 'TurboVNC: levrek165.yonetim:1 (user)' started on display levrek165.yonetim:1

Log file is vnc.log
Successfully started VNC server on levrek165.yonetim:5901...
Script starting...
Starting websocket server...
+ module load centos7.3/app/R/4.0.2-gcc
++ /usr/bin/modulecmd bash load centos7.3/app/R/4.0.2-gcc
+ xfwm4 --compositor=off --daemon --sm-client-disable
+ eval LD_LIBRARY_PATH=/truba/sw/centos7.3/app/R/4.0.2/lib64 ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=centos7.3/app/R/4.0.2-gcc' ';export' 'LOADEDMODULES;PATH=/truba/sw/centos7.3/app/R/4.0.2/bin:/opt/TurboVNC/bin:/truba/home/user/anaconda3/condabin:/usr/lib64/qt-3.3/bin:/truba/home/user/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin' ';export' 'PATH;R_DIR=/truba/sw/centos7.3/app/R/4.0.2' ';export' 'R_DIR;_LMFILES_=/truba/sw/centos7.3/modulefiles/centos7.3/app/R/4.0.2-gcc' ';export' '_LMFILES_;'
++ LD_LIBRARY_PATH=/truba/sw/centos7.3/app/R/4.0.2/lib64
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=centos7.3/app/R/4.0.2-gcc
++ export LOADEDMODULES
++ PATH=/truba/sw/centos7.3/app/R/4.0.2/bin:/opt/TurboVNC/bin:/truba/home/user/anaconda3/condabin:/usr/lib64/qt-3.3/bin:/truba/home/user/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin
++ export PATH
++ R_DIR=/truba/sw/centos7.3/app/R/4.0.2
++ export R_DIR
++ _LMFILES_=/truba/sw/centos7.3/modulefiles/centos7.3/app/R/4.0.2-gcc
++ export _LMFILES_
+ rstudio

(xfwm4:18065): GLib-CRITICAL **: 10:15:57.396: g_str_has_prefix: assertion 'prefix != NULL' failed
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/5886', please create it with 0700 permissions.

(xfwm4:18065): xfwm4-WARNING **: 10:15:57.413: The property '/general/double_click_distance' of type int is not supported
+ xsetroot -solid '#D3D3D3'
+ xfsettingsd --sm-client-disable
+ xfconf-query -c xfwm4 -p /general/workspace_count -s 1

(xfsettingsd:18116): GLib-CRITICAL **: 10:15:57.695: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:18116): GLib-GObject-CRITICAL **: 10:15:57.696: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:18116): GLib-GObject-CRITICAL **: 10:15:57.697: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
Failed to create secure directory (/run/user/5886/pulse): No such file or directory
WebSocket server settings:
  - Listen on :64072
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
Scanning VNC log file for user authentications...
Generating connection YAML file...
Setting VNC password...
Generating connection YAML file...
Setting VNC password...
Generating connection YAML file...
Cleaning up...
Killing Xvnc process ID 18024
xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
`
**R'da hiç bir pakaetim aşağıdaki hata mesajı nedeniyle çalışmıyor.** 

`Error: package or namespace load failed for ?ggpubr? in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/truba/home/user/R/x86_64-pc-linux-gnu-library/4.0/stringi/libs/stringi.so':
  /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /truba/home/user/R/x86_64-pc-linux-gnu-library/4.0/stringi/libs/stringi.so)`

`Error: package or namespace load failed for ?stringi? in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/truba/home/user/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-stringi/00new/stringi/libs/stringi.so':
  lib64/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /truba/home/user/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-stringi/00new/stringi/libs/stringi.so)
Error: loading failed
Execution halted`

**String komutuyla taramdığımda bu dosyalar mevcut değil. Örneğim 3.4.19 var ama 3.4.20 yok. 
Bu hata mesajının anaconda ve logdaki hatalarla ilgisi sizce var mı? Condayı deactive ettiğim halde log dosyasında oturum başlatma aşamasında yine ancondanın path edildiğini izliyorum. Bu durumu nasıl düzeltebileceğimi bilemiyorum. Ekibe yazdım ancak bayram ve tam kapanmadan dolayı ya da çok ypun olduklarından henüz yanıt alamadım. Bir öneriniz var mı.**

**Comment by keremkayabay** [comment]
Merhaba,
Sorunun açıldığı tarihte eski wiki'yi yeni sisteme taşırken yaşadığımız yoğunluktan dolayı cevap yazamadık. Aynı problemin yaşanmaması için Open OnDemand için Jupyter kurulumunun https://docs.truba.gov.tr/how-to-guides/python/anaconda.html#jupyter-anaconda adresindeki yönergelerin takip edilerek yapılması uygun olacaktır.
